title: ADHDeveloper
owner: ADHD Developer
email: developer@adhdeveloper.com
description: Thoughts about technology, software development, business and other assorted things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tech.adhdeveloper.com" # the base hostname & protocol for your site, e.g. http://example.com
language: en
#twitter_username:
#github_username:
#disqus_username:
# Build settings
markdown: kramdown
theme: minima

permalink: /:year/:month/:day/:title/

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
excerpt_separator: <!--more-->
